### ISSUE TITLE
在 get_batch 时出现 bug

### ISSUE THREAD

**Issue by daccding** [Rokid/ELMo-chinese#2]
请问用您传的中文数据集跑elmo时出现这个错误

```sh
Traceback (most recent call last):
  File "train_elmo.py", line 72, in <module>
    main(args)
  File "train_elmo.py", line 62, in main
    train(options, data, n_gpus, tf_save_dir, tf_log_dir)
  File "/mnt/disk2/data/wp/Word2vec/model/ELMo-chinese/bin/bilm/training.py", line 838, in train
    for batch_no, batch in enumerate(data_gen, start=1):
  File "/mnt/disk2/data/wp/Word2vec/model/ELMo-chinese/bin/bilm/data.py", line 469, in iter_batches
    num_steps, max_word_length)
  File "/mnt/disk2/data/wp/Word2vec/model/ELMo-chinese/bin/bilm/data.py", line 311, in _get_batch
    :how_many]
ValueError: could not broadcast input array from shape (18,50) into shape (19,50)

```
最后发现是 `bilm/data.py` 下的 `get_bacth` 函数的:

```py
  inputs[i, cur_pos:next_pos] = cur_stream[i][0][:how_many]
                if max_word_length is not None:
                    char_inputs[i, cur_pos:next_pos] = cur_stream[i][1][:
                                                                        how_many]
```

这一段报错。
由于没看懂 `get_batch` 的逻辑，自己不会改，请问能指点一下吗，谢谢

**Comment by guotong1988** [comment]
vocab用pre_data文件夹下的代码预处理出来，vocab忘了更新了

**Comment by guotong1988** [comment]
好像不是vocab的问题，正在修复

**Comment by guotong1988** [comment]
现在修复了
